GENTOO_COMMIT=abdb7522fe5f609ecd70959b1a95e67e76daa351
CROSSDEV_TOOLCHAIN=llvm
CROSSDEV_TARGET=aarch64-unknown-linux-musl
CROSSDEV_PROFILE=default/linux/arm64/23.0/split-usr/musl/llvm
CROSSDEV_EXTRA_ARGS=--llvm
