#!/bin/bash

SYSROOT=/usr/x86_64-unknown-linux-musl
LD_MUSL_ARCH=x86_64
LIBPATH="$(x86_64-unknown-linux-musl-clang -print-search-dirs \
	| sed -n 's/^libraries: =//p')"

exec "${SYSROOT}/lib/ld-musl-${LD_MUSL_ARCH}.so.1" \
	--library-path "$LIBPATH" "$@"
