CHOST=x86_64-unknown-linux-musl

ROOT=/usr/${CHOST}/

ACCEPT_KEYWORDS="${ARCH}"

USE="${ARCH}"

# Keep the compile flags vanilla.
COMMON_FLAGS="-O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8
