name: Build container images

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  IMAGE: ghcr.io/${{ github.repository_owner }}/crossdev

jobs:
  build:
    runs-on: ${{ matrix.host.runner }}
    strategy:
      fail-fast: false
      matrix:
        host:
          - runner: ubuntu-latest
            platform: linux/amd64
            tag-prefix: amd64
          # FIXME: Gets stuck on the GitHub runners, reason yet unknown.
          # - runner: ubuntu-24.04-arm
          #   platform: linux/arm64
          #   tag-prefix: arm64
        target:
          - llvm-aarch64-unknown-linux-musl
          - llvm-riscv64-unknown-linux-musl
          - llvm-x86_64-unknown-linux-musl
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: Dockerfile
          image: ${{ env.IMAGE }}
          tags: ${{ format('{0}-{1}', matrix.host.tag-prefix, matrix.target) }}
          platforms: ${{ matrix.host.platform }}
          extra-args: |
            --build-arg-file ${{ matrix.target }}/build-args.conf

      - name: Create image archive
        run: |
          buildah push \
            "${{ env.IMAGE }}:${{ matrix.host.tag-prefix }}-${{ matrix.target }}" \
            "oci-archive:${{ matrix.host.tag-prefix }}-${{ matrix.target }}.tar"

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ format('{0}-{1}', matrix.host.tag-prefix, matrix.target) }}
          path: ${{ format('{0}-{1}.tar', matrix.host.tag-prefix, matrix.target) }}
          if-no-files-found: error
          retention-days: 1

  manifest:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - llvm-aarch64-unknown-linux-musl
          - llvm-riscv64-unknown-linux-musl
          - llvm-x86_64-unknown-linux-musl
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to GHCR
        if: github.event_name == 'push'
        run: |
          set -euxo pipefail
          buildah login --username "${{ github.actor }}" --password-stdin ghcr.io \
            <<< "${{ secrets.GITHUB_TOKEN }}"

      - uses: actions/download-artifact@v4
        with:
          pattern: ${{ format('*-{0}', matrix.target) }}
          path: artifacts
          merge-multiple: true

      - name: Create multi-platform manifest
        run: |
          set -euxo pipefail
          buildah manifest create "${{ env.IMAGE }}:${{ matrix.target }}"
          shopt -s nullglob
          for archive in artifacts/*; do
            image_id=$(buildah pull "oci-archive:${archive}")
            buildah manifest add "${{ env.IMAGE }}:${{ matrix.target }}" \
              "containers-storage:${image_id}"
          done

      - name: Push multi-platform manifest
        if: github.event_name == 'push'
        run: |
          buildah manifest push --all "${{ env.IMAGE }}:${{ matrix.target }}" \
            "docker://${{ env.IMAGE }}:${{ matrix.target }}"
